//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PotterDraw.rc
//
#define IDR_MAINFRAME                   101
#define IDR_MAINFRAME_256               102
#define IDR_PALETTE_BAR                 103
#define IDR_POPUP_EDIT                  104
#define IDR_POTTERDRAWTYPE              105
#define IDR_PROPERTIES                  106
#define IDR_SPLINE                      107
#define IDR_THEME_MENU                  108
#define IDD_ABOUTBOX                    109
#define IDD_GRID_SETUP                  110
#define IDD_OPTIONS                     111
#define IDD_RECORD                      112
#define IDD_RECORD_STATUS               113
#define IDD_ROTATE                      114
#define IDD_ROTATE_2D                   115
#define IDD_SCALE_2D                    116
#define IDD_TRANSLATE_2D                117
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_CKUP_CANT_GET_ADDR          203
#define IDS_CKUP_CANT_LOAD_DLL          204
#define IDS_DDV_PCT_CANT_BE_100         205
#define IDS_DDV_PCT_MUST_BE_GT_ZERO     206
#define IDS_DDV_VAL_CANT_BE_ZERO        207
#define IDS_DOC_BAD_FORMAT              208
#define IDS_DOC_NEWER_VERSION           209
#define IDS_EDIT_MENU                   210
#define IDS_EDIT_REDO_FMT               211
#define IDS_EDIT_UNDO_FMT               212
#define IDS_ERR_BAD_EXPORT_TYPE         213
#define IDS_ERR_CANT_COPY_TEXTURE_FILE  214
#define IDS_ERR_CANT_CREATE_DIRECT3D    215
#define IDS_ERR_CANT_CREATE_DIRECT3D_DEVICE 216
#define IDS_ERR_CANT_CREATE_MM_TIMER    217
#define IDS_ERR_CANT_CREATE_MM_TIMER_PERIOD 218
#define IDS_ERR_CANT_CREATE_TEXTURE_BITMAP 219
#define IDS_ERR_CANT_WRITE_TEXTURE_BITMAP 220
#define IDS_ERR_EXPORT_FAILED           221
#define IDS_ERR_SPLINE_DUPLICATE_Y      222
#define IDS_ERR_SPLINE_EMPTY            223
#define IDS_ERR_SPLINE_NEGATIVE_X       224
#define IDS_ERR_TEXTURE_FILE_NOT_FOUND  225
#define IDS_ERR_TEXTURE_TOO_WIDE        226
#define IDS_EXPLORER                    227
#define IDS_EXPORT                      228
#define IDS_HLINK_CANT_LAUNCH           229
#define IDS_MODULATION_BAR              230
#define IDS_MOD_DESC_fAmplitude         231
#define IDS_MOD_DESC_fBias              232
#define IDS_MOD_DESC_fFrequency         233
#define IDS_MOD_DESC_fPhase             234
#define IDS_MOD_DESC_fPhaseSpeed        235
#define IDS_MOD_DESC_fPower             236
#define IDS_MOD_DESC_fPulseWidth        237
#define IDS_MOD_DESC_fSlew              238
#define IDS_MOD_DESC_iMotif             239
#define IDS_MOD_DESC_iOperation         240
#define IDS_MOD_DESC_iRange             241
#define IDS_MOD_DESC_iTarget            242
#define IDS_MOD_DESC_iWaveform          243
#define IDS_MOD_GROUP_MAIN              244
#define IDS_MOD_NAME_fAmplitude         245
#define IDS_MOD_NAME_fBias              246
#define IDS_MOD_NAME_fFrequency         247
#define IDS_MOD_NAME_fPhase             248
#define IDS_MOD_NAME_fPhaseSpeed        249
#define IDS_MOD_NAME_fPower             250
#define IDS_MOD_NAME_fPulseWidth        251
#define IDS_MOD_NAME_fSlew              252
#define IDS_MOD_NAME_iMotif             253
#define IDS_MOD_NAME_iOperation         254
#define IDS_MOD_NAME_iRange             255
#define IDS_MOD_NAME_iTarget            256
#define IDS_MOD_NAME_iWaveform          257
#define IDS_MOD_OPT_OPER_ADD            258
#define IDS_MOD_OPT_OPER_DIVIDE         259
#define IDS_MOD_OPT_OPER_EXPONENTIATE   260
#define IDS_MOD_OPT_OPER_MULTIPLY       261
#define IDS_MOD_OPT_OPER_SUBTRACT       262
#define IDS_MOD_OPT_RANGE_BIPOLAR       263
#define IDS_MOD_OPT_RANGE_UNIPOLAR      264
#define IDS_MOD_OPT_WAVE_FLAME          265
#define IDS_MOD_OPT_WAVE_NONE           266
#define IDS_MOD_OPT_WAVE_PULSE          267
#define IDS_MOD_OPT_WAVE_RAMP_DOWN      268
#define IDS_MOD_OPT_WAVE_RAMP_UP        269
#define IDS_MOD_OPT_WAVE_ROUNDED_PULSE  270
#define IDS_MOD_OPT_WAVE_SINE           271
#define IDS_MOD_OPT_WAVE_SINE_CUBED     272
#define IDS_MOD_OPT_WAVE_SQUARE         273
#define IDS_MOD_OPT_WAVE_TRIANGLE       274
#define IDS_MOD_OPT_WAVE_TRIANGULAR_PULSE 275
#define IDS_OPT_DESC_bAutoCheckUpdates  276
#define IDS_OPT_DESC_bCustomImageSize   277
#define IDS_OPT_DESC_bPlotAllModulations 278
#define IDS_OPT_DESC_bPropertyDescrips  279
#define IDS_OPT_DESC_bVertexColor       280
#define IDS_OPT_DESC_bViewSplineDrag    281
#define IDS_OPT_DESC_fDragRotateStep    282
#define IDS_OPT_DESC_fPanStep           283
#define IDS_OPT_DESC_fSplineZoomStep    284
#define IDS_OPT_DESC_fZoomStep          285
#define IDS_OPT_DESC_nCustomImageHeight 286
#define IDS_OPT_DESC_nCustomImageWidth  287
#define IDS_OPT_DESC_nFloatPrecision    288
#define IDS_OPT_GROUP_EXPORT            289
#define IDS_OPT_GROUP_GENERAL           290
#define IDS_OPT_GROUP_OSCILLOSCOPE      291
#define IDS_OPT_GROUP_SPLINE            292
#define IDS_OPT_GROUP_VIEW              293
#define IDS_OPT_NAME_bAutoCheckUpdates  294
#define IDS_OPT_NAME_bCustomImageSize   295
#define IDS_OPT_NAME_bPlotAllModulations 296
#define IDS_OPT_NAME_bPropertyDescrips  297
#define IDS_OPT_NAME_bVertexColor       298
#define IDS_OPT_NAME_bViewSplineDrag    299
#define IDS_OPT_NAME_fDragRotateStep    300
#define IDS_OPT_NAME_fPanStep           301
#define IDS_OPT_NAME_fSplineZoomStep    302
#define IDS_OPT_NAME_fZoomStep          303
#define IDS_OPT_NAME_nCustomImageHeight 304
#define IDS_OPT_NAME_nCustomImageWidth  305
#define IDS_OPT_NAME_nFloatPrecision    306
#define IDS_OSCILLOSCOPE_BAR            307
#define IDS_PALETTE_BAR                 308
#define IDS_PALETTE_BAR_APPLY           309
#define IDS_PALETTE_BAR_DELETE          310
#define IDS_PALETTE_BAR_INSERT          311
#define IDS_PDR_DESC_bAnimation         312
#define IDS_PDR_DESC_clrBackground      313
#define IDS_PDR_DESC_fAspectRatio       314
#define IDS_PDR_DESC_fAutoRotatePitch   315
#define IDS_PDR_DESC_fAutoRotateRoll    316
#define IDS_PDR_DESC_fAutoRotateYaw     317
#define IDS_PDR_DESC_fBendDepth         318
#define IDS_PDR_DESC_fBendPhase         319
#define IDS_PDR_DESC_fBendPolePhase     320
#define IDS_PDR_DESC_fBendPoles         321
#define IDS_PDR_DESC_fBends             322
#define IDS_PDR_DESC_fColorCycles       323
#define IDS_PDR_DESC_fCyclesV           324
#define IDS_PDR_DESC_fFrameRate         325
#define IDS_PDR_DESC_fHelixAmplitude    326
#define IDS_PDR_DESC_fHelixFrequency    327
#define IDS_PDR_DESC_fOffsetU           328
#define IDS_PDR_DESC_fOffsetV           329
#define IDS_PDR_DESC_fPetals            330
#define IDS_PDR_DESC_fRadius            331
#define IDS_PDR_DESC_fRippleDepth       332
#define IDS_PDR_DESC_fRipplePhase       333
#define IDS_PDR_DESC_fRipples           334
#define IDS_PDR_DESC_fScallopDepth      335
#define IDS_PDR_DESC_fScallopPhase      336
#define IDS_PDR_DESC_fScallopPower      337
#define IDS_PDR_DESC_fScallopPulseWidth 338
#define IDS_PDR_DESC_fScallopSlew       339
#define IDS_PDR_DESC_fScallops          340
#define IDS_PDR_DESC_fStripeAmplitude   341
#define IDS_PDR_DESC_fStripeFrequency   342
#define IDS_PDR_DESC_fStripePhase       343
#define IDS_PDR_DESC_fTwist             344
#define IDS_PDR_DESC_fWallThickness     345
#define IDS_PDR_DESC_iBendMotif         346
#define IDS_PDR_DESC_iBendPoleMotif     347
#define IDS_PDR_DESC_iColorPattern      348
#define IDS_PDR_DESC_iPaletteType       349
#define IDS_PDR_DESC_iRippleMotif       350
#define IDS_PDR_DESC_iScallopMotif      351
#define IDS_PDR_DESC_iScallopOperation  352
#define IDS_PDR_DESC_iScallopRange      353
#define IDS_PDR_DESC_iScallopWaveform   354
#define IDS_PDR_DESC_nColorSharpness    355
#define IDS_PDR_DESC_nColors            356
#define IDS_PDR_DESC_nRings             357
#define IDS_PDR_DESC_nSides             358
#define IDS_PDR_DESC_sTexturePath       359
#define IDS_PDR_GROUP_MESH              360
#define IDS_PDR_GROUP_TEXTURE           361
#define IDS_PDR_GROUP_VIEW              362
#define IDS_PDR_NAME_bAnimation         363
#define IDS_PDR_NAME_clrBackground      364
#define IDS_PDR_NAME_fAspectRatio       365
#define IDS_PDR_NAME_fAutoRotatePitch   366
#define IDS_PDR_NAME_fAutoRotateRoll    367
#define IDS_PDR_NAME_fAutoRotateYaw     368
#define IDS_PDR_NAME_fBendDepth         369
#define IDS_PDR_NAME_fBendPhase         370
#define IDS_PDR_NAME_fBendPolePhase     371
#define IDS_PDR_NAME_fBendPoles         372
#define IDS_PDR_NAME_fBends             373
#define IDS_PDR_NAME_fColorCycles       374
#define IDS_PDR_NAME_fCyclesV           375
#define IDS_PDR_NAME_fFrameRate         376
#define IDS_PDR_NAME_fHelixAmplitude    377
#define IDS_PDR_NAME_fHelixFrequency    378
#define IDS_PDR_NAME_fOffsetU           379
#define IDS_PDR_NAME_fOffsetV           380
#define IDS_PDR_NAME_fPetals            381
#define IDS_PDR_NAME_fRadius            382
#define IDS_PDR_NAME_fRippleDepth       383
#define IDS_PDR_NAME_fRipplePhase       384
#define IDS_PDR_NAME_fRipples           385
#define IDS_PDR_NAME_fScallopDepth      386
#define IDS_PDR_NAME_fScallopPhase      387
#define IDS_PDR_NAME_fScallopPower      388
#define IDS_PDR_NAME_fScallopPulseWidth 389
#define IDS_PDR_NAME_fScallopSlew       390
#define IDS_PDR_NAME_fScallops          391
#define IDS_PDR_NAME_fStripeAmplitude   392
#define IDS_PDR_NAME_fStripeFrequency   393
#define IDS_PDR_NAME_fStripePhase       394
#define IDS_PDR_NAME_fTwist             395
#define IDS_PDR_NAME_fWallThickness     396
#define IDS_PDR_NAME_iBendMotif         397
#define IDS_PDR_NAME_iBendPoleMotif     398
#define IDS_PDR_NAME_iColorPattern      399
#define IDS_PDR_NAME_iPaletteType       400
#define IDS_PDR_NAME_iRippleMotif       401
#define IDS_PDR_NAME_iScallopMotif      402
#define IDS_PDR_NAME_iScallopOperation  403
#define IDS_PDR_NAME_iScallopRange      404
#define IDS_PDR_NAME_iScallopWaveform   405
#define IDS_PDR_NAME_nColorSharpness    406
#define IDS_PDR_NAME_nColors            407
#define IDS_PDR_NAME_nRings             408
#define IDS_PDR_NAME_nSides             409
#define IDS_PDR_NAME_sTexturePath       410
#define IDS_PDR_OPT_COLPAT_PETALS       411
#define IDS_PDR_OPT_COLPAT_POLAR        412
#define IDS_PDR_OPT_COLPAT_RINGS        413
#define IDS_PDR_OPT_COLPAT_STRIPES      414
#define IDS_PDR_OPT_MOTIF_FLUTES        415
#define IDS_PDR_OPT_MOTIF_NONE          416
#define IDS_PDR_OPT_MOTIF_PARTED_FLUTES 417
#define IDS_PDR_OPT_MOTIF_PARTED_REEDS  418
#define IDS_PDR_OPT_MOTIF_REEDS         419
#define IDS_PDR_OPT_PALTYPE_COMPLEMENT  420
#define IDS_PDR_OPT_PALTYPE_LINEAR      421
#define IDS_PDR_OPT_PALTYPE_SPLIT       422
#define IDS_PROPERTIES_BAR              423
#define IDS_PROPS_MORE_COLORS           424
#define IDS_RECDLG_CUSTOM               425
#define IDS_RECORD_FOLDER               426
#define IDS_RESET_ALL_OPTIONS           427
#define IDS_SCALE_2D_SCALE              428
#define IDS_SCALE_2D_WIDTH              429
#define IDS_SPLINE_BAR                  430
#define IDS_SPLINE_NM_ADD_NODE          431
#define IDS_SPLINE_NM_CHANGED           432
#define IDS_SPLINE_NM_CUT               433
#define IDS_SPLINE_NM_DELETE            434
#define IDS_SPLINE_NM_DELETE_NODE       435
#define IDS_SPLINE_NM_FLIP_HORIZONTAL   436
#define IDS_SPLINE_NM_FLIP_VERTICAL     437
#define IDS_SPLINE_NM_IMPORT            438
#define IDS_SPLINE_NM_NODE_TYPE         439
#define IDS_SPLINE_NM_PASTE             440
#define IDS_SPLINE_NM_ROTATE            441
#define IDS_SPLINE_NM_SCALE             442
#define IDS_SPLINE_NM_SEGMENT_TYPE      443
#define IDS_SPLINE_NM_TRANSLATE         444
#define IDS_TEXTURE_FILES               445
#define IDS_TEXT_FILES_FILTER           446
#define IDS_TOOLBAR_CUSTOMIZE           447
#define IDS_TOOLBAR_STANDARD            448
#define IDS_VIEW_PAN                    449
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_MAGNIFIER            1003
#define IDC_DRAG_SINGLE                 1004
#define IDC_GRID_SPACING                1005
#define IDC_OPTIONS_GRID                1006
#define IDC_OPTIONS_RESET_ALL           1007
#define IDC_RECORD_ANIMATION            1008
#define IDC_RECORD_AUTO_ROTATE          1009
#define IDC_RECORD_DURATION             1010
#define IDC_RECORD_DURATION_UNIT        1011
#define IDC_RECORD_DURATION_UNIT2       1012
#define IDC_RECORD_FILE_FORMAT          1013
#define IDC_RECORD_FRAME_HEIGHT         1014
#define IDC_RECORD_FRAME_HEIGHT_CAP     1015
#define IDC_RECORD_FRAME_RATE           1016
#define IDC_RECORD_FRAME_SIZE           1017
#define IDC_RECORD_FRAME_WIDTH          1018
#define IDC_RECORD_FRAME_WIDTH_CAP      1019
#define IDC_RECORD_STATUS_COMPLETED     1020
#define IDC_RECORD_STATUS_DURATION      1021
#define IDC_RECORD_STATUS_PROGRESS      1022
#define IDC_RECORD_STATUS_REMAINING     1023
#define IDC_ROTATE_ANGLE                1024
#define IDC_ROTATE_X                    1025
#define IDC_ROTATE_Y                    1026
#define IDC_ROTATE_Z                    1027
#define IDC_SCALE_HEIGHT                1028
#define IDC_SCALE_HEIGHT_CAPTION        1029
#define IDC_SCALE_HEIGHT_UNIT           1030
#define IDC_SCALE_PROPORTIONALLY        1031
#define IDC_SCALE_RELATIVE_TO           1032
#define IDC_SCALE_RELATIVE_TO2          1033
#define IDC_SCALE_WIDTH                 1034
#define IDC_SCALE_WIDTH_CAPTION         1035
#define IDC_TRANSLATE_X                 1036
#define IDC_TRANSLATE_Y                 1037
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_DESELECT                32774
#define ID_EDIT_INSERT                  32775
#define ID_EXPAND_ALL                   32776
#define ID_FILE_EXPORT                  32777
#define ID_FILE_LOAD_TEXTURE            32778
#define ID_FILE_RECORD                  32779
#define ID_INDICATOR_FRAME_RATE         32780
#define ID_INDICATOR_RESOLUTION         32781
#define ID_INDICATOR_ZOOM               32782
#define ID_PROPERTIES1                  32783
#define ID_PROPERTIES2                  32784
#define ID_SORTPROPERTIES               32785
#define ID_SPLINE_ADD_NODE              32786
#define ID_SPLINE_DELETE_NODE           32787
#define ID_SPLINE_EXPORT                32788
#define ID_SPLINE_FLIP_HORIZONTAL       32789
#define ID_SPLINE_FLIP_VERTICAL         32790
#define ID_SPLINE_GRID_SETUP            32791
#define ID_SPLINE_IMPORT                32792
#define ID_SPLINE_NODE_TYPE1_CUSP       32793
#define ID_SPLINE_NODE_TYPE2_SMOOTH     32794
#define ID_SPLINE_NODE_TYPE3_SYMMETRICAL 32795
#define ID_SPLINE_ROTATE                32796
#define ID_SPLINE_SCALE                 32797
#define ID_SPLINE_SEGMENT_TYPE1_CURVE   32798
#define ID_SPLINE_SEGMENT_TYPE2_LINE    32799
#define ID_SPLINE_SHOW_GRID             32800
#define ID_SPLINE_SHOW_HORZ_MIRROR      32801
#define ID_SPLINE_SHOW_RULERS           32802
#define ID_SPLINE_SNAP_TO_GRID          32803
#define ID_SPLINE_TRANSLATE             32804
#define ID_SPLINE_ZOOM_IN               32805
#define ID_SPLINE_ZOOM_OUT              32806
#define ID_SPLINE_ZOOM_RESET            32807
#define ID_TOOLS_MESH_INFO              32808
#define ID_TOOLS_OPTIONS                32809
#define ID_VIEW_APPLOOK_MDI_TABS        32810
#define ID_VIEW_APPLOOK_OFF_2003        32811
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32812
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32813
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32814
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32815
#define ID_VIEW_APPLOOK_OFF_XP          32816
#define ID_VIEW_APPLOOK_VS_2005         32817
#define ID_VIEW_APPLOOK_VS_2008         32818
#define ID_VIEW_APPLOOK_WINDOWS_7       32819
#define ID_VIEW_APPLOOK_WIN_2000        32820
#define ID_VIEW_APPLOOK_WIN_XP          32821
#define ID_VIEW_CUSTOMIZE               32822
#define ID_VIEW_PAN_DOWN                32823
#define ID_VIEW_PAN_EDIT                32824
#define ID_VIEW_PAN_LEFT                32825
#define ID_VIEW_PAN_RIGHT               32826
#define ID_VIEW_PAN_UP                  32827
#define ID_VIEW_RECORD_STATUS           32828
#define ID_VIEW_ROTATE_ABOVE            32829
#define ID_VIEW_ROTATE_AUTO             32830
#define ID_VIEW_ROTATE_BACK             32831
#define ID_VIEW_ROTATE_BOTTOM           32832
#define ID_VIEW_ROTATE_EDIT             32833
#define ID_VIEW_ROTATE_FRONT            32834
#define ID_VIEW_ROTATE_LEFT             32835
#define ID_VIEW_ROTATE_RESET            32836
#define ID_VIEW_ROTATE_RIGHT            32837
#define ID_VIEW_ROTATE_TOP              32838
#define ID_VIEW_STYLE_ANIMATION         32839
#define ID_VIEW_STYLE_BOUNDS            32840
#define ID_VIEW_STYLE_CULLING           32841
#define ID_VIEW_STYLE_GOURAUD           32842
#define ID_VIEW_STYLE_HIGHLIGHTS        32843
#define ID_VIEW_STYLE_TEXTURE           32844
#define ID_VIEW_STYLE_WIREFRAME         32845
#define ID_VIEW_ZOOM_IN                 32846
#define ID_VIEW_ZOOM_OUT                32847
#define ID_VIEW_ZOOM_RESET              32848
#define ID_WINDOW_FULL_SCREEN           32849
#define ID_WINDOW_MANAGER               32850

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        450
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
