//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PotterDraw.rc
//
#define IDR_MAINFRAME                   101
#define IDR_MAINFRAME_256               102
#define IDR_PALETTE_BAR                 103
#define IDR_POPUP_EDIT                  104
#define IDR_POTTERDRAWTYPE              105
#define IDR_PROPERTIES                  106
#define IDR_SPLINE                      107
#define IDR_THEME_MENU                  108
#define IDD_ABOUTBOX                    109
#define IDD_GRID_SETUP                  110
#define IDD_OPTIONS                     111
#define IDD_RECORD                      112
#define IDD_RECORD_STATUS               113
#define IDD_ROTATE                      114
#define IDD_ROTATE_2D                   115
#define IDD_SCALE_2D                    116
#define IDD_TRANSLATE_2D                117
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_DDV_PCT_CANT_BE_100         203
#define IDS_DDV_PCT_MUST_BE_GT_ZERO     204
#define IDS_DDV_VAL_CANT_BE_ZERO        205
#define IDS_DOC_BAD_FORMAT              206
#define IDS_DOC_NEWER_VERSION           207
#define IDS_EDIT_MENU                   208
#define IDS_EDIT_REDO_FMT               209
#define IDS_EDIT_UNDO_FMT               210
#define IDS_ERR_BAD_EXPORT_TYPE         211
#define IDS_ERR_CANT_COPY_TEXTURE_FILE  212
#define IDS_ERR_CANT_CREATE_DIRECT3D    213
#define IDS_ERR_CANT_CREATE_DIRECT3D_DEVICE 214
#define IDS_ERR_CANT_CREATE_MM_TIMER    215
#define IDS_ERR_CANT_CREATE_MM_TIMER_PERIOD 216
#define IDS_ERR_CANT_CREATE_TEXTURE_BITMAP 217
#define IDS_ERR_CANT_WRITE_TEXTURE_BITMAP 218
#define IDS_ERR_EXPORT_FAILED           219
#define IDS_ERR_SPLINE_DUPLICATE_Y      220
#define IDS_ERR_SPLINE_EMPTY            221
#define IDS_ERR_SPLINE_NEGATIVE_X       222
#define IDS_ERR_TEXTURE_FILE_NOT_FOUND  223
#define IDS_EXPLORER                    224
#define IDS_EXPORT                      225
#define IDS_HLINK_CANT_LAUNCH           226
#define IDS_MODULATION_BAR              227
#define IDS_MOD_DESC_fAmplitude         228
#define IDS_MOD_DESC_fBias              229
#define IDS_MOD_DESC_fFrequency         230
#define IDS_MOD_DESC_fPhase             231
#define IDS_MOD_DESC_fPhaseSpeed        232
#define IDS_MOD_DESC_fPower             233
#define IDS_MOD_DESC_iMotif             234
#define IDS_MOD_DESC_iOperation         235
#define IDS_MOD_DESC_iRange             236
#define IDS_MOD_DESC_iTarget            237
#define IDS_MOD_DESC_iWaveform          238
#define IDS_MOD_GROUP_MAIN              239
#define IDS_MOD_NAME_fAmplitude         240
#define IDS_MOD_NAME_fBias              241
#define IDS_MOD_NAME_fFrequency         242
#define IDS_MOD_NAME_fPhase             243
#define IDS_MOD_NAME_fPhaseSpeed        244
#define IDS_MOD_NAME_fPower             245
#define IDS_MOD_NAME_iMotif             246
#define IDS_MOD_NAME_iOperation         247
#define IDS_MOD_NAME_iRange             248
#define IDS_MOD_NAME_iTarget            249
#define IDS_MOD_NAME_iWaveform          250
#define IDS_MOD_OPT_OPER_ADD            251
#define IDS_MOD_OPT_OPER_DIVIDE         252
#define IDS_MOD_OPT_OPER_MULTIPLY       253
#define IDS_MOD_OPT_OPER_SUBTRACT       254
#define IDS_MOD_OPT_RANGE_BIPOLAR       255
#define IDS_MOD_OPT_RANGE_UNIPOLAR      256
#define IDS_MOD_OPT_WAVE_NONE           257
#define IDS_MOD_OPT_WAVE_RAMP_DOWN      258
#define IDS_MOD_OPT_WAVE_RAMP_UP        259
#define IDS_MOD_OPT_WAVE_SINE           260
#define IDS_MOD_OPT_WAVE_SQUARE         261
#define IDS_MOD_OPT_WAVE_TRIANGLE       262
#define IDS_OPT_DESC_bCustomImageSize   263
#define IDS_OPT_DESC_bPlotAllModulations 264
#define IDS_OPT_DESC_bPropertyDescrips  265
#define IDS_OPT_DESC_bVertexColor       266
#define IDS_OPT_DESC_fDragRotateStep    267
#define IDS_OPT_DESC_fPanStep           268
#define IDS_OPT_DESC_fSplineZoomStep    269
#define IDS_OPT_DESC_fZoomStep          270
#define IDS_OPT_DESC_nCustomImageHeight 271
#define IDS_OPT_DESC_nCustomImageWidth  272
#define IDS_OPT_DESC_nFloatPrecision    273
#define IDS_OPT_GROUP_EXPORT            274
#define IDS_OPT_GROUP_GENERAL           275
#define IDS_OPT_GROUP_OSCILLOSCOPE      276
#define IDS_OPT_GROUP_SPLINE            277
#define IDS_OPT_GROUP_VIEW              278
#define IDS_OPT_NAME_bCustomImageSize   279
#define IDS_OPT_NAME_bPlotAllModulations 280
#define IDS_OPT_NAME_bPropertyDescrips  281
#define IDS_OPT_NAME_bVertexColor       282
#define IDS_OPT_NAME_fDragRotateStep    283
#define IDS_OPT_NAME_fPanStep           284
#define IDS_OPT_NAME_fSplineZoomStep    285
#define IDS_OPT_NAME_fZoomStep          286
#define IDS_OPT_NAME_nCustomImageHeight 287
#define IDS_OPT_NAME_nCustomImageWidth  288
#define IDS_OPT_NAME_nFloatPrecision    289
#define IDS_OSCILLOSCOPE_BAR            290
#define IDS_PALETTE_BAR                 291
#define IDS_PALETTE_BAR_APPLY           292
#define IDS_PALETTE_BAR_DELETE          293
#define IDS_PALETTE_BAR_INSERT          294
#define IDS_PDR_DESC_bAnimation         295
#define IDS_PDR_DESC_clrBackground      296
#define IDS_PDR_DESC_fAspectRatio       297
#define IDS_PDR_DESC_fAutoRotatePitch   298
#define IDS_PDR_DESC_fAutoRotateRoll    299
#define IDS_PDR_DESC_fAutoRotateYaw     300
#define IDS_PDR_DESC_fBendDepth         301
#define IDS_PDR_DESC_fBendPhase         302
#define IDS_PDR_DESC_fBendPolePhase     303
#define IDS_PDR_DESC_fBendPoles         304
#define IDS_PDR_DESC_fBends             305
#define IDS_PDR_DESC_fColorCycles       306
#define IDS_PDR_DESC_fCyclesV           307
#define IDS_PDR_DESC_fFrameRate         308
#define IDS_PDR_DESC_fHelixAmplitude    309
#define IDS_PDR_DESC_fHelixFrequency    310
#define IDS_PDR_DESC_fOffsetU           311
#define IDS_PDR_DESC_fOffsetV           312
#define IDS_PDR_DESC_fPetals            313
#define IDS_PDR_DESC_fRadius            314
#define IDS_PDR_DESC_fRippleDepth       315
#define IDS_PDR_DESC_fRipplePhase       316
#define IDS_PDR_DESC_fRipples           317
#define IDS_PDR_DESC_fScallopDepth      318
#define IDS_PDR_DESC_fScallops          319
#define IDS_PDR_DESC_fStripeAmplitude   320
#define IDS_PDR_DESC_fStripeFrequency   321
#define IDS_PDR_DESC_fStripePhase       322
#define IDS_PDR_DESC_fTwist             323
#define IDS_PDR_DESC_fWallThickness     324
#define IDS_PDR_DESC_iBendMotif         325
#define IDS_PDR_DESC_iBendPoleMotif     326
#define IDS_PDR_DESC_iColorPattern      327
#define IDS_PDR_DESC_iPaletteType       328
#define IDS_PDR_DESC_iRippleMotif       329
#define IDS_PDR_DESC_iScallopMotif      330
#define IDS_PDR_DESC_nColorSharpness    331
#define IDS_PDR_DESC_nColors            332
#define IDS_PDR_DESC_nRings             333
#define IDS_PDR_DESC_nSides             334
#define IDS_PDR_DESC_sTexturePath       335
#define IDS_PDR_GROUP_MESH              336
#define IDS_PDR_GROUP_TEXTURE           337
#define IDS_PDR_GROUP_VIEW              338
#define IDS_PDR_NAME_bAnimation         339
#define IDS_PDR_NAME_clrBackground      340
#define IDS_PDR_NAME_fAspectRatio       341
#define IDS_PDR_NAME_fAutoRotatePitch   342
#define IDS_PDR_NAME_fAutoRotateRoll    343
#define IDS_PDR_NAME_fAutoRotateYaw     344
#define IDS_PDR_NAME_fBendDepth         345
#define IDS_PDR_NAME_fBendPhase         346
#define IDS_PDR_NAME_fBendPolePhase     347
#define IDS_PDR_NAME_fBendPoles         348
#define IDS_PDR_NAME_fBends             349
#define IDS_PDR_NAME_fColorCycles       350
#define IDS_PDR_NAME_fCyclesV           351
#define IDS_PDR_NAME_fFrameRate         352
#define IDS_PDR_NAME_fHelixAmplitude    353
#define IDS_PDR_NAME_fHelixFrequency    354
#define IDS_PDR_NAME_fOffsetU           355
#define IDS_PDR_NAME_fOffsetV           356
#define IDS_PDR_NAME_fPetals            357
#define IDS_PDR_NAME_fRadius            358
#define IDS_PDR_NAME_fRippleDepth       359
#define IDS_PDR_NAME_fRipplePhase       360
#define IDS_PDR_NAME_fRipples           361
#define IDS_PDR_NAME_fScallopDepth      362
#define IDS_PDR_NAME_fScallops          363
#define IDS_PDR_NAME_fStripeAmplitude   364
#define IDS_PDR_NAME_fStripeFrequency   365
#define IDS_PDR_NAME_fStripePhase       366
#define IDS_PDR_NAME_fTwist             367
#define IDS_PDR_NAME_fWallThickness     368
#define IDS_PDR_NAME_iBendMotif         369
#define IDS_PDR_NAME_iBendPoleMotif     370
#define IDS_PDR_NAME_iColorPattern      371
#define IDS_PDR_NAME_iPaletteType       372
#define IDS_PDR_NAME_iRippleMotif       373
#define IDS_PDR_NAME_iScallopMotif      374
#define IDS_PDR_NAME_nColorSharpness    375
#define IDS_PDR_NAME_nColors            376
#define IDS_PDR_NAME_nRings             377
#define IDS_PDR_NAME_nSides             378
#define IDS_PDR_NAME_sTexturePath       379
#define IDS_PDR_OPT_COLPAT_PETALS       380
#define IDS_PDR_OPT_COLPAT_POLAR        381
#define IDS_PDR_OPT_COLPAT_RINGS        382
#define IDS_PDR_OPT_COLPAT_STRIPES      383
#define IDS_PDR_OPT_MOTIF_FLUTES        384
#define IDS_PDR_OPT_MOTIF_NONE          385
#define IDS_PDR_OPT_MOTIF_PARTED_FLUTES 386
#define IDS_PDR_OPT_MOTIF_PARTED_REEDS  387
#define IDS_PDR_OPT_MOTIF_REEDS         388
#define IDS_PDR_OPT_PALTYPE_COMPLEMENT  389
#define IDS_PDR_OPT_PALTYPE_LINEAR      390
#define IDS_PDR_OPT_PALTYPE_SPLIT       391
#define IDS_PROPERTIES_BAR              392
#define IDS_PROPS_MORE_COLORS           393
#define IDS_RECDLG_CUSTOM               394
#define IDS_RECORD_FOLDER               395
#define IDS_RESET_ALL_OPTIONS           396
#define IDS_SCALE_2D_SCALE              397
#define IDS_SCALE_2D_WIDTH              398
#define IDS_SPLINE_BAR                  399
#define IDS_SPLINE_NM_ADD_NODE          400
#define IDS_SPLINE_NM_CHANGED           401
#define IDS_SPLINE_NM_CUT               402
#define IDS_SPLINE_NM_DELETE            403
#define IDS_SPLINE_NM_DELETE_NODE       404
#define IDS_SPLINE_NM_FLIP_HORIZONTAL   405
#define IDS_SPLINE_NM_FLIP_VERTICAL     406
#define IDS_SPLINE_NM_IMPORT            407
#define IDS_SPLINE_NM_NODE_TYPE         408
#define IDS_SPLINE_NM_PASTE             409
#define IDS_SPLINE_NM_ROTATE            410
#define IDS_SPLINE_NM_SCALE             411
#define IDS_SPLINE_NM_SEGMENT_TYPE      412
#define IDS_SPLINE_NM_TRANSLATE         413
#define IDS_TEXT_FILES_FILTER           414
#define IDS_TOOLBAR_CUSTOMIZE           415
#define IDS_TOOLBAR_STANDARD            416
#define IDS_VIEW_PAN                    417
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_MAGNIFIER            1003
#define IDC_DRAG_SINGLE                 1004
#define IDC_GRID_SPACING                1005
#define IDC_OPTIONS_GRID                1006
#define IDC_OPTIONS_RESET_ALL           1007
#define IDC_RECORD_ANIMATION            1008
#define IDC_RECORD_AUTO_ROTATE          1009
#define IDC_RECORD_DURATION             1010
#define IDC_RECORD_DURATION_UNIT        1011
#define IDC_RECORD_DURATION_UNIT2       1012
#define IDC_RECORD_FILE_FORMAT          1013
#define IDC_RECORD_FRAME_HEIGHT         1014
#define IDC_RECORD_FRAME_HEIGHT_CAP     1015
#define IDC_RECORD_FRAME_RATE           1016
#define IDC_RECORD_FRAME_SIZE           1017
#define IDC_RECORD_FRAME_WIDTH          1018
#define IDC_RECORD_FRAME_WIDTH_CAP      1019
#define IDC_RECORD_STATUS_COMPLETED     1020
#define IDC_RECORD_STATUS_DURATION      1021
#define IDC_RECORD_STATUS_PROGRESS      1022
#define IDC_ROTATE_ANGLE                1023
#define IDC_ROTATE_X                    1024
#define IDC_ROTATE_Y                    1025
#define IDC_ROTATE_Z                    1026
#define IDC_SCALE_HEIGHT                1027
#define IDC_SCALE_HEIGHT_CAPTION        1028
#define IDC_SCALE_HEIGHT_UNIT           1029
#define IDC_SCALE_PROPORTIONALLY        1030
#define IDC_SCALE_RELATIVE_TO           1031
#define IDC_SCALE_RELATIVE_TO2          1032
#define IDC_SCALE_WIDTH                 1033
#define IDC_SCALE_WIDTH_CAPTION         1034
#define IDC_TRANSLATE_X                 1035
#define IDC_TRANSLATE_Y                 1036
#define ID_APP_HOME_PAGE                32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_DESELECT                32773
#define ID_EDIT_INSERT                  32774
#define ID_EXPAND_ALL                   32775
#define ID_FILE_EXPORT                  32776
#define ID_FILE_RECORD                  32777
#define ID_INDICATOR_FRAME_RATE         32778
#define ID_INDICATOR_RESOLUTION         32779
#define ID_INDICATOR_ZOOM               32780
#define ID_PROPERTIES1                  32781
#define ID_PROPERTIES2                  32782
#define ID_SORTPROPERTIES               32783
#define ID_SPLINE_ADD_NODE              32784
#define ID_SPLINE_DELETE_NODE           32785
#define ID_SPLINE_EXPORT                32786
#define ID_SPLINE_FLIP_HORIZONTAL       32787
#define ID_SPLINE_FLIP_VERTICAL         32788
#define ID_SPLINE_GRID_SETUP            32789
#define ID_SPLINE_IMPORT                32790
#define ID_SPLINE_NODE_TYPE1_CUSP       32791
#define ID_SPLINE_NODE_TYPE2_SMOOTH     32792
#define ID_SPLINE_NODE_TYPE3_SYMMETRICAL 32793
#define ID_SPLINE_ROTATE                32794
#define ID_SPLINE_SCALE                 32795
#define ID_SPLINE_SEGMENT_TYPE1_CURVE   32796
#define ID_SPLINE_SEGMENT_TYPE2_LINE    32797
#define ID_SPLINE_SHOW_GRID             32798
#define ID_SPLINE_SHOW_HORZ_MIRROR      32799
#define ID_SPLINE_SHOW_RULERS           32800
#define ID_SPLINE_SNAP_TO_GRID          32801
#define ID_SPLINE_TRANSLATE             32802
#define ID_SPLINE_ZOOM_IN               32803
#define ID_SPLINE_ZOOM_OUT              32804
#define ID_SPLINE_ZOOM_RESET            32805
#define ID_TOOLS_MESH_INFO              32806
#define ID_TOOLS_OPTIONS                32807
#define ID_VIEW_APPLOOK_MDI_TABS        32808
#define ID_VIEW_APPLOOK_OFF_2003        32809
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32810
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32811
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32812
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32813
#define ID_VIEW_APPLOOK_OFF_XP          32814
#define ID_VIEW_APPLOOK_VS_2005         32815
#define ID_VIEW_APPLOOK_VS_2008         32816
#define ID_VIEW_APPLOOK_WINDOWS_7       32817
#define ID_VIEW_APPLOOK_WIN_2000        32818
#define ID_VIEW_APPLOOK_WIN_XP          32819
#define ID_VIEW_CUSTOMIZE               32820
#define ID_VIEW_PAN_DOWN                32821
#define ID_VIEW_PAN_EDIT                32822
#define ID_VIEW_PAN_LEFT                32823
#define ID_VIEW_PAN_RIGHT               32824
#define ID_VIEW_PAN_UP                  32825
#define ID_VIEW_RECORD_STATUS           32826
#define ID_VIEW_ROTATE_ABOVE            32827
#define ID_VIEW_ROTATE_AUTO             32828
#define ID_VIEW_ROTATE_BACK             32829
#define ID_VIEW_ROTATE_BOTTOM           32830
#define ID_VIEW_ROTATE_EDIT             32831
#define ID_VIEW_ROTATE_FRONT            32832
#define ID_VIEW_ROTATE_LEFT             32833
#define ID_VIEW_ROTATE_RESET            32834
#define ID_VIEW_ROTATE_RIGHT            32835
#define ID_VIEW_ROTATE_TOP              32836
#define ID_VIEW_STYLE_ANIMATION         32837
#define ID_VIEW_STYLE_BOUNDS            32838
#define ID_VIEW_STYLE_CULLING           32839
#define ID_VIEW_STYLE_GOURAUD           32840
#define ID_VIEW_STYLE_HIGHLIGHTS        32841
#define ID_VIEW_STYLE_TEXTURE           32842
#define ID_VIEW_STYLE_WIREFRAME         32843
#define ID_VIEW_ZOOM_IN                 32844
#define ID_VIEW_ZOOM_OUT                32845
#define ID_VIEW_ZOOM_RESET              32846
#define ID_WINDOW_FULL_SCREEN           32847
#define ID_WINDOW_MANAGER               32848

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        418
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
