//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PotterDraw.rc
//
#define IDR_MAINFRAME                   101
#define IDR_MAINFRAME_256               102
#define IDR_PALETTE_BAR                 103
#define IDR_POPUP_EDIT                  104
#define IDR_POTTERDRAWTYPE              105
#define IDR_PROPERTIES                  106
#define IDR_SPLINE                      107
#define IDR_THEME_MENU                  108
#define IDD_ABOUTBOX                    109
#define IDD_GRID_SETUP                  110
#define IDD_LIGHTING                    111
#define IDD_OPTIONS                     112
#define IDD_RECORD                      113
#define IDD_RECORD_STATUS               114
#define IDD_ROTATE                      115
#define IDD_ROTATE_2D                   116
#define IDD_SCALE_2D                    117
#define IDD_TRANSLATE_2D                118
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_CKUP_CANT_GET_ADDR          203
#define IDS_CKUP_CANT_LOAD_DLL          204
#define IDS_DDV_PCT_CANT_BE_100         205
#define IDS_DDV_PCT_MUST_BE_GT_ZERO     206
#define IDS_DDV_VAL_CANT_BE_ZERO        207
#define IDS_DOC_BAD_FORMAT              208
#define IDS_DOC_NEWER_VERSION           209
#define IDS_EDIT_MENU                   210
#define IDS_EDIT_REDO_FMT               211
#define IDS_EDIT_UNDO_FMT               212
#define IDS_ERR_BAD_EXPORT_TYPE         213
#define IDS_ERR_CANT_COPY_TEXTURE_FILE  214
#define IDS_ERR_CANT_CREATE_DIRECT3D    215
#define IDS_ERR_CANT_CREATE_DIRECT3D_DEVICE 216
#define IDS_ERR_CANT_CREATE_MM_TIMER    217
#define IDS_ERR_CANT_CREATE_MM_TIMER_PERIOD 218
#define IDS_ERR_CANT_CREATE_TEXTURE_BITMAP 219
#define IDS_ERR_CANT_WRITE_TEXTURE_BITMAP 220
#define IDS_ERR_EXPORT_FAILED           221
#define IDS_ERR_SPLINE_DUPLICATE_Y      222
#define IDS_ERR_SPLINE_EMPTY            223
#define IDS_ERR_SPLINE_NEGATIVE_X       224
#define IDS_ERR_TEXTURE_FILE_NOT_FOUND  225
#define IDS_ERR_TEXTURE_TOO_WIDE        226
#define IDS_EXPLORER                    227
#define IDS_EXPORT                      228
#define IDS_HLINK_CANT_LAUNCH           229
#define IDS_MESH_INFO_FORMAT            230
#define IDS_MODULATION_BAR              231
#define IDS_MOD_DESC_fAmplitude         232
#define IDS_MOD_DESC_fBias              233
#define IDS_MOD_DESC_fFrequency         234
#define IDS_MOD_DESC_fPhase             235
#define IDS_MOD_DESC_fPhaseSpeed        236
#define IDS_MOD_DESC_fPower             237
#define IDS_MOD_DESC_fPulseWidth        238
#define IDS_MOD_DESC_fSlew              239
#define IDS_MOD_DESC_iModType           240
#define IDS_MOD_DESC_iMotif             241
#define IDS_MOD_DESC_iOperation         242
#define IDS_MOD_DESC_iPowerType         243
#define IDS_MOD_DESC_iRange             244
#define IDS_MOD_DESC_iTarget            245
#define IDS_MOD_DESC_iWaveform          246
#define IDS_MOD_GROUP_MAIN              247
#define IDS_MOD_NAME_fAmplitude         248
#define IDS_MOD_NAME_fBias              249
#define IDS_MOD_NAME_fFrequency         250
#define IDS_MOD_NAME_fPhase             251
#define IDS_MOD_NAME_fPhaseSpeed        252
#define IDS_MOD_NAME_fPower             253
#define IDS_MOD_NAME_fPulseWidth        254
#define IDS_MOD_NAME_fSlew              255
#define IDS_MOD_NAME_iModType           256
#define IDS_MOD_NAME_iMotif             257
#define IDS_MOD_NAME_iOperation         258
#define IDS_MOD_NAME_iPowerType         259
#define IDS_MOD_NAME_iRange             260
#define IDS_MOD_NAME_iTarget            261
#define IDS_MOD_NAME_iWaveform          262
#define IDS_MOD_OPT_OPER_ADD            263
#define IDS_MOD_OPT_OPER_DIVIDE         264
#define IDS_MOD_OPT_OPER_EXPONENTIATE   265
#define IDS_MOD_OPT_OPER_MULTIPLY       266
#define IDS_MOD_OPT_OPER_SUBTRACT       267
#define IDS_MOD_OPT_POWER_TYPE_ASYMMETRIC 268
#define IDS_MOD_OPT_POWER_TYPE_SYMMETRIC 269
#define IDS_MOD_OPT_RANGE_BIPOLAR       270
#define IDS_MOD_OPT_RANGE_UNIPOLAR      271
#define IDS_MOD_OPT_WAVE_CIRCULAR_PULSE 272
#define IDS_MOD_OPT_WAVE_FLAME          273
#define IDS_MOD_OPT_WAVE_NONE           274
#define IDS_MOD_OPT_WAVE_PULSE          275
#define IDS_MOD_OPT_WAVE_RAMP_DOWN      276
#define IDS_MOD_OPT_WAVE_RAMP_PULSE     277
#define IDS_MOD_OPT_WAVE_RAMP_UP        278
#define IDS_MOD_OPT_WAVE_ROUNDED_PULSE  279
#define IDS_MOD_OPT_WAVE_SEMICIRCLE     280
#define IDS_MOD_OPT_WAVE_SINE           281
#define IDS_MOD_OPT_WAVE_SINE_CUBED     282
#define IDS_MOD_OPT_WAVE_SQUARE         283
#define IDS_MOD_OPT_WAVE_TRIANGLE       284
#define IDS_MOD_OPT_WAVE_TRIANGULAR_PULSE 285
#define IDS_MOD_TYPE_PROPERTY           286
#define IDS_OPT_DESC_bAutoCheckUpdates  287
#define IDS_OPT_DESC_bCustomImageSize   288
#define IDS_OPT_DESC_bPlotAllModulations 289
#define IDS_OPT_DESC_bPropertyDescrips  290
#define IDS_OPT_DESC_bVertexColor       291
#define IDS_OPT_DESC_bViewSplineDrag    292
#define IDS_OPT_DESC_fDragRotateStep    293
#define IDS_OPT_DESC_fPanStep           294
#define IDS_OPT_DESC_fSplineZoomStep    295
#define IDS_OPT_DESC_fZoomStep          296
#define IDS_OPT_DESC_nCustomImageHeight 297
#define IDS_OPT_DESC_nCustomImageWidth  298
#define IDS_OPT_DESC_nFloatPrecision    299
#define IDS_OPT_GROUP_EXPORT            300
#define IDS_OPT_GROUP_GENERAL           301
#define IDS_OPT_GROUP_OSCILLOSCOPE      302
#define IDS_OPT_GROUP_SPLINE            303
#define IDS_OPT_GROUP_VIEW              304
#define IDS_OPT_NAME_bAutoCheckUpdates  305
#define IDS_OPT_NAME_bCustomImageSize   306
#define IDS_OPT_NAME_bPlotAllModulations 307
#define IDS_OPT_NAME_bPropertyDescrips  308
#define IDS_OPT_NAME_bVertexColor       309
#define IDS_OPT_NAME_bViewSplineDrag    310
#define IDS_OPT_NAME_fDragRotateStep    311
#define IDS_OPT_NAME_fPanStep           312
#define IDS_OPT_NAME_fSplineZoomStep    313
#define IDS_OPT_NAME_fZoomStep          314
#define IDS_OPT_NAME_nCustomImageHeight 315
#define IDS_OPT_NAME_nCustomImageWidth  316
#define IDS_OPT_NAME_nFloatPrecision    317
#define IDS_OSCILLOSCOPE_BAR            318
#define IDS_PALETTE_BAR                 319
#define IDS_PALETTE_BAR_APPLY           320
#define IDS_PALETTE_BAR_DELETE          321
#define IDS_PALETTE_BAR_INSERT          322
#define IDS_PALETTE_FILES_FILTER        323
#define IDS_PDR_DESC_bAnimation         324
#define IDS_PDR_DESC_clrBackground      325
#define IDS_PDR_DESC_fAspectRatio       326
#define IDS_PDR_DESC_fAutoRotatePitch   327
#define IDS_PDR_DESC_fAutoRotateRoll    328
#define IDS_PDR_DESC_fAutoRotateYaw     329
#define IDS_PDR_DESC_fAutoRotateZoom    330
#define IDS_PDR_DESC_fBendDepth         331
#define IDS_PDR_DESC_fBendPhase         332
#define IDS_PDR_DESC_fBendPolePhase     333
#define IDS_PDR_DESC_fBendPoles         334
#define IDS_PDR_DESC_fBendPower         335
#define IDS_PDR_DESC_fBends             336
#define IDS_PDR_DESC_fColorCycles       337
#define IDS_PDR_DESC_fCyclesV           338
#define IDS_PDR_DESC_fEdgeGain          339
#define IDS_PDR_DESC_fFrameRate         340
#define IDS_PDR_DESC_fHelixAmplitude    341
#define IDS_PDR_DESC_fHelixFrequency    342
#define IDS_PDR_DESC_fOffsetU           343
#define IDS_PDR_DESC_fOffsetV           344
#define IDS_PDR_DESC_fPetals            345
#define IDS_PDR_DESC_fPolygonBulge      346
#define IDS_PDR_DESC_fPolygonPhase      347
#define IDS_PDR_DESC_fPolygonRoundness  348
#define IDS_PDR_DESC_fPolygonSides      349
#define IDS_PDR_DESC_fRadius            350
#define IDS_PDR_DESC_fRingPhase         351
#define IDS_PDR_DESC_fRippleDepth       352
#define IDS_PDR_DESC_fRipplePhase       353
#define IDS_PDR_DESC_fRipplePower       354
#define IDS_PDR_DESC_fRipples           355
#define IDS_PDR_DESC_fRuffleDepth       356
#define IDS_PDR_DESC_fRufflePhase       357
#define IDS_PDR_DESC_fRufflePower       358
#define IDS_PDR_DESC_fRufflePulseWidth  359
#define IDS_PDR_DESC_fRuffleSlew        360
#define IDS_PDR_DESC_fRuffles           361
#define IDS_PDR_DESC_fScallopDepth      362
#define IDS_PDR_DESC_fScallopPhase      363
#define IDS_PDR_DESC_fScallopPower      364
#define IDS_PDR_DESC_fScallopPulseWidth 365
#define IDS_PDR_DESC_fScallopSlew       366
#define IDS_PDR_DESC_fScallops          367
#define IDS_PDR_DESC_fStripeAmplitude   368
#define IDS_PDR_DESC_fStripeFrequency   369
#define IDS_PDR_DESC_fStripePhase       370
#define IDS_PDR_DESC_fTwist             371
#define IDS_PDR_DESC_fWallThickness     372
#define IDS_PDR_DESC_iBendMotif         373
#define IDS_PDR_DESC_iBendOperation     374
#define IDS_PDR_DESC_iBendPoleMotif     375
#define IDS_PDR_DESC_iBendPowerType     376
#define IDS_PDR_DESC_iColorPattern      377
#define IDS_PDR_DESC_iPaletteType       378
#define IDS_PDR_DESC_iRippleMotif       379
#define IDS_PDR_DESC_iRippleOperation   380
#define IDS_PDR_DESC_iRipplePowerType   381
#define IDS_PDR_DESC_iRuffleMotif       382
#define IDS_PDR_DESC_iRufflePowerType   383
#define IDS_PDR_DESC_iRuffleWaveform    384
#define IDS_PDR_DESC_iScallopMotif      385
#define IDS_PDR_DESC_iScallopOperation  386
#define IDS_PDR_DESC_iScallopPowerType  387
#define IDS_PDR_DESC_iScallopRange      388
#define IDS_PDR_DESC_iScallopWaveform   389
#define IDS_PDR_DESC_nColorSharpness    390
#define IDS_PDR_DESC_nColors            391
#define IDS_PDR_DESC_nRings             392
#define IDS_PDR_DESC_nSides             393
#define IDS_PDR_DESC_sTexturePath       394
#define IDS_PDR_GROUP_MESH              395
#define IDS_PDR_GROUP_TEXTURE           396
#define IDS_PDR_GROUP_VIEW              397
#define IDS_PDR_NAME_bAnimation         398
#define IDS_PDR_NAME_clrBackground      399
#define IDS_PDR_NAME_fAspectRatio       400
#define IDS_PDR_NAME_fAutoRotatePitch   401
#define IDS_PDR_NAME_fAutoRotateRoll    402
#define IDS_PDR_NAME_fAutoRotateYaw     403
#define IDS_PDR_NAME_fAutoRotateZoom    404
#define IDS_PDR_NAME_fBendDepth         405
#define IDS_PDR_NAME_fBendPhase         406
#define IDS_PDR_NAME_fBendPolePhase     407
#define IDS_PDR_NAME_fBendPoles         408
#define IDS_PDR_NAME_fBendPower         409
#define IDS_PDR_NAME_fBends             410
#define IDS_PDR_NAME_fColorCycles       411
#define IDS_PDR_NAME_fCyclesV           412
#define IDS_PDR_NAME_fEdgeGain          413
#define IDS_PDR_NAME_fFrameRate         414
#define IDS_PDR_NAME_fHelixAmplitude    415
#define IDS_PDR_NAME_fHelixFrequency    416
#define IDS_PDR_NAME_fOffsetU           417
#define IDS_PDR_NAME_fOffsetV           418
#define IDS_PDR_NAME_fPetals            419
#define IDS_PDR_NAME_fPolygonBulge      420
#define IDS_PDR_NAME_fPolygonPhase      421
#define IDS_PDR_NAME_fPolygonRoundness  422
#define IDS_PDR_NAME_fPolygonSides      423
#define IDS_PDR_NAME_fRadius            424
#define IDS_PDR_NAME_fRingPhase         425
#define IDS_PDR_NAME_fRippleDepth       426
#define IDS_PDR_NAME_fRipplePhase       427
#define IDS_PDR_NAME_fRipplePower       428
#define IDS_PDR_NAME_fRipples           429
#define IDS_PDR_NAME_fRuffleDepth       430
#define IDS_PDR_NAME_fRufflePhase       431
#define IDS_PDR_NAME_fRufflePower       432
#define IDS_PDR_NAME_fRufflePulseWidth  433
#define IDS_PDR_NAME_fRuffleSlew        434
#define IDS_PDR_NAME_fRuffles           435
#define IDS_PDR_NAME_fScallopDepth      436
#define IDS_PDR_NAME_fScallopPhase      437
#define IDS_PDR_NAME_fScallopPower      438
#define IDS_PDR_NAME_fScallopPulseWidth 439
#define IDS_PDR_NAME_fScallopSlew       440
#define IDS_PDR_NAME_fScallops          441
#define IDS_PDR_NAME_fStripeAmplitude   442
#define IDS_PDR_NAME_fStripeFrequency   443
#define IDS_PDR_NAME_fStripePhase       444
#define IDS_PDR_NAME_fTwist             445
#define IDS_PDR_NAME_fWallThickness     446
#define IDS_PDR_NAME_iBendMotif         447
#define IDS_PDR_NAME_iBendOperation     448
#define IDS_PDR_NAME_iBendPoleMotif     449
#define IDS_PDR_NAME_iBendPowerType     450
#define IDS_PDR_NAME_iColorPattern      451
#define IDS_PDR_NAME_iPaletteType       452
#define IDS_PDR_NAME_iRippleMotif       453
#define IDS_PDR_NAME_iRippleOperation   454
#define IDS_PDR_NAME_iRipplePowerType   455
#define IDS_PDR_NAME_iRuffleMotif       456
#define IDS_PDR_NAME_iRufflePowerType   457
#define IDS_PDR_NAME_iRuffleWaveform    458
#define IDS_PDR_NAME_iScallopMotif      459
#define IDS_PDR_NAME_iScallopOperation  460
#define IDS_PDR_NAME_iScallopPowerType  461
#define IDS_PDR_NAME_iScallopRange      462
#define IDS_PDR_NAME_iScallopWaveform   463
#define IDS_PDR_NAME_nColorSharpness    464
#define IDS_PDR_NAME_nColors            465
#define IDS_PDR_NAME_nRings             466
#define IDS_PDR_NAME_nSides             467
#define IDS_PDR_NAME_sTexturePath       468
#define IDS_PDR_OPT_COLPAT_AZIMUTH      469
#define IDS_PDR_OPT_COLPAT_AZI_INC      470
#define IDS_PDR_OPT_COLPAT_EDGES        471
#define IDS_PDR_OPT_COLPAT_INCLINE      472
#define IDS_PDR_OPT_COLPAT_PETALS       473
#define IDS_PDR_OPT_COLPAT_POLAR        474
#define IDS_PDR_OPT_COLPAT_RADIUS       475
#define IDS_PDR_OPT_COLPAT_RINGS        476
#define IDS_PDR_OPT_COLPAT_STRIPES      477
#define IDS_PDR_OPT_MOTIF_FLUTES        478
#define IDS_PDR_OPT_MOTIF_INVERT        479
#define IDS_PDR_OPT_MOTIF_NONE          480
#define IDS_PDR_OPT_MOTIF_PARTED_FLUTES 481
#define IDS_PDR_OPT_MOTIF_PARTED_REEDS  482
#define IDS_PDR_OPT_MOTIF_REEDS         483
#define IDS_PDR_OPT_PALTYPE_COMPLEMENT  484
#define IDS_PDR_OPT_PALTYPE_LINEAR      485
#define IDS_PDR_OPT_PALTYPE_SPLIT       486
#define IDS_PDR_SUBGROUP_MESH_BEND      487
#define IDS_PDR_SUBGROUP_MESH_HELIX     488
#define IDS_PDR_SUBGROUP_MESH_POLYGON   489
#define IDS_PDR_SUBGROUP_MESH_RIPPLE    490
#define IDS_PDR_SUBGROUP_MESH_RUFFLE    491
#define IDS_PDR_SUBGROUP_MESH_SCALLOP   492
#define IDS_PDR_SUBGROUP_VIEW_AUTOROTATE 493
#define IDS_PROPERTIES_BAR              494
#define IDS_PROPS_MORE_COLORS           495
#define IDS_RECDLG_CUSTOM               496
#define IDS_RECORD_FOLDER               497
#define IDS_RESET_ALL_OPTIONS           498
#define IDS_SCALE_2D_SCALE              499
#define IDS_SCALE_2D_WIDTH              500
#define IDS_SPLINE_BAR                  501
#define IDS_SPLINE_NM_ADD_NODE          502
#define IDS_SPLINE_NM_CHANGED           503
#define IDS_SPLINE_NM_CUT               504
#define IDS_SPLINE_NM_DELETE            505
#define IDS_SPLINE_NM_DELETE_NODE       506
#define IDS_SPLINE_NM_FLIP_HORIZONTAL   507
#define IDS_SPLINE_NM_FLIP_VERTICAL     508
#define IDS_SPLINE_NM_IMPORT            509
#define IDS_SPLINE_NM_NODE_TYPE         510
#define IDS_SPLINE_NM_PASTE             511
#define IDS_SPLINE_NM_ROTATE            512
#define IDS_SPLINE_NM_SCALE             513
#define IDS_SPLINE_NM_SEGMENT_TYPE      514
#define IDS_SPLINE_NM_TRANSLATE         515
#define IDS_TEXTURE_FILES               516
#define IDS_TEXT_FILES_FILTER           517
#define IDS_TOOLBAR_CUSTOMIZE           518
#define IDS_TOOLBAR_STANDARD            519
#define IDS_UNDO_LIGHTING               520
#define IDS_UNDO_RANDOM_PHASE           521
#define IDS_UNDO_STEP_ANIMATION         522
#define IDS_VIEW_PAN                    523
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_MAGNIFIER            1003
#define IDC_DRAG_SINGLE                 1004
#define IDC_GRID_SPACING                1005
#define IDC_LIGHTING_AMBIENT            1006
#define IDC_LIGHTING_DIFFUSE            1007
#define IDC_LIGHTING_DIR_X              1008
#define IDC_LIGHTING_DIR_Y              1009
#define IDC_LIGHTING_DIR_Z              1010
#define IDC_LIGHTING_POWER              1011
#define IDC_LIGHTING_RESET              1012
#define IDC_LIGHTING_SPECULAR           1013
#define IDC_OPTIONS_GRID                1014
#define IDC_OPTIONS_RESET_ALL           1015
#define IDC_RECORD_ANIMATION            1016
#define IDC_RECORD_AUTO_ROTATE          1017
#define IDC_RECORD_DURATION             1018
#define IDC_RECORD_DURATION_UNIT        1019
#define IDC_RECORD_DURATION_UNIT2       1020
#define IDC_RECORD_FILE_FORMAT          1021
#define IDC_RECORD_FRAME_HEIGHT         1022
#define IDC_RECORD_FRAME_HEIGHT_CAP     1023
#define IDC_RECORD_FRAME_RATE           1024
#define IDC_RECORD_FRAME_SIZE           1025
#define IDC_RECORD_FRAME_WIDTH          1026
#define IDC_RECORD_FRAME_WIDTH_CAP      1027
#define IDC_RECORD_STATUS_COMPLETED     1028
#define IDC_RECORD_STATUS_DURATION      1029
#define IDC_RECORD_STATUS_PROGRESS      1030
#define IDC_RECORD_STATUS_REMAINING     1031
#define IDC_ROTATE_ANGLE                1032
#define IDC_ROTATE_X                    1033
#define IDC_ROTATE_Y                    1034
#define IDC_ROTATE_Z                    1035
#define IDC_SCALE_HEIGHT                1036
#define IDC_SCALE_HEIGHT_CAPTION        1037
#define IDC_SCALE_HEIGHT_UNIT           1038
#define IDC_SCALE_PROPORTIONALLY        1039
#define IDC_SCALE_RELATIVE_TO           1040
#define IDC_SCALE_RELATIVE_TO2          1041
#define IDC_SCALE_WIDTH                 1042
#define IDC_SCALE_WIDTH_CAPTION         1043
#define IDC_TRANSLATE_X                 1044
#define IDC_TRANSLATE_Y                 1045
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_DESELECT                32774
#define ID_EDIT_INSERT                  32775
#define ID_EXPAND_ALL                   32776
#define ID_FILE_EXPORT                  32777
#define ID_FILE_LOAD_TEXTURE            32778
#define ID_FILE_RECORD                  32779
#define ID_INDICATOR_FRAME_RATE         32780
#define ID_INDICATOR_RESOLUTION         32781
#define ID_INDICATOR_ZOOM               32782
#define ID_PALETTE_EXPORT               32783
#define ID_PALETTE_IMPORT               32784
#define ID_PROPERTIES1                  32785
#define ID_PROPERTIES2                  32786
#define ID_RENDER_BOUNDS                32787
#define ID_RENDER_CULLING               32788
#define ID_RENDER_GOURAUD               32789
#define ID_RENDER_HIGHLIGHTS            32790
#define ID_RENDER_LIGHTING              32791
#define ID_RENDER_TEXTURE               32792
#define ID_RENDER_TRANSPARENT           32793
#define ID_RENDER_WIREFRAME             32794
#define ID_SORTPROPERTIES               32795
#define ID_SPLINE_ADD_NODE              32796
#define ID_SPLINE_DELETE_NODE           32797
#define ID_SPLINE_EXPORT                32798
#define ID_SPLINE_FLIP_HORIZONTAL       32799
#define ID_SPLINE_FLIP_VERTICAL         32800
#define ID_SPLINE_GRID_SETUP            32801
#define ID_SPLINE_IMPORT                32802
#define ID_SPLINE_NODE_TYPE1_CUSP       32803
#define ID_SPLINE_NODE_TYPE2_SMOOTH     32804
#define ID_SPLINE_NODE_TYPE3_SYMMETRICAL 32805
#define ID_SPLINE_ROTATE                32806
#define ID_SPLINE_SCALE                 32807
#define ID_SPLINE_SEGMENT_TYPE1_CURVE   32808
#define ID_SPLINE_SEGMENT_TYPE2_LINE    32809
#define ID_SPLINE_SHOW_GRID             32810
#define ID_SPLINE_SHOW_HORZ_MIRROR      32811
#define ID_SPLINE_SHOW_RULERS           32812
#define ID_SPLINE_SNAP_TO_GRID          32813
#define ID_SPLINE_TRANSLATE             32814
#define ID_SPLINE_ZOOM_IN               32815
#define ID_SPLINE_ZOOM_OUT              32816
#define ID_SPLINE_ZOOM_RESET            32817
#define ID_TOOLS_MESH_INFO              32818
#define ID_TOOLS_OPTIONS                32819
#define ID_VIEW_ANIMATION               32820
#define ID_VIEW_APPLOOK_MDI_TABS        32821
#define ID_VIEW_APPLOOK_OFF_2003        32822
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32823
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32824
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32825
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32826
#define ID_VIEW_APPLOOK_OFF_XP          32827
#define ID_VIEW_APPLOOK_VS_2005         32828
#define ID_VIEW_APPLOOK_VS_2008         32829
#define ID_VIEW_APPLOOK_WINDOWS_7       32830
#define ID_VIEW_APPLOOK_WIN_2000        32831
#define ID_VIEW_APPLOOK_WIN_XP          32832
#define ID_VIEW_CUSTOMIZE               32833
#define ID_VIEW_PAN_DOWN                32834
#define ID_VIEW_PAN_EDIT                32835
#define ID_VIEW_PAN_LEFT                32836
#define ID_VIEW_PAN_RIGHT               32837
#define ID_VIEW_PAN_UP                  32838
#define ID_VIEW_RANDOM_PHASE            32839
#define ID_VIEW_RECORD_STATUS           32840
#define ID_VIEW_ROTATE_ABOVE            32841
#define ID_VIEW_ROTATE_AUTO             32842
#define ID_VIEW_ROTATE_BACK             32843
#define ID_VIEW_ROTATE_BOTTOM           32844
#define ID_VIEW_ROTATE_EDIT             32845
#define ID_VIEW_ROTATE_FRONT            32846
#define ID_VIEW_ROTATE_LEFT             32847
#define ID_VIEW_ROTATE_RESET            32848
#define ID_VIEW_ROTATE_RIGHT            32849
#define ID_VIEW_ROTATE_TOP              32850
#define ID_VIEW_STEP_BACKWARD           32851
#define ID_VIEW_STEP_FORWARD            32852
#define ID_VIEW_ZOOM_IN                 32853
#define ID_VIEW_ZOOM_OUT                32854
#define ID_VIEW_ZOOM_RESET              32855
#define ID_WINDOW_FULL_SCREEN           32856
#define ID_WINDOW_MANAGER               32857

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        524
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
